key_manager:
  network: "regtest"
  mnemonic_sentence: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

storage:
  password: "secret_password"
  path: "/tmp/storage.db"